In [47]:
import nltk
from nltk.corpus import movie_reviews
nltk.download('movie_reviews')
nltk.download('punkt')

[nltk_data] Downloading package movie_reviews to
[nltk_data]     /Users/jacobrodriguez/nltk_data...
[nltk_data]   Unzipping corpora/movie_reviews.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/jacobrodriguez/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [2]:
# remove punctuation first
import string
no_punct = [''.join(c for c in s if c not in string.punctuation) for s in movie_reviews.words()]
new_list = [s for s in no_punct if s]
new_list

['plot',
 'two',
 'teen',
 'couples',
 'go',
 'to',
 'a',
 'church',
 'party',
 'drink',
 'and',
 'then',
 'drive',
 'they',
 'get',
 'into',
 'an',
 'accident',
 'one',
 'of',
 'the',
 'guys',
 'dies',
 'but',
 'his',
 'girlfriend',
 'continues',
 'to',
 'see',
 'him',
 'in',
 'her',
 'life',
 'and',
 'has',
 'nightmares',
 'what',
 's',
 'the',
 'deal',
 'watch',
 'the',
 'movie',
 'and',
 'sorta',
 'find',
 'out',
 'critique',
 'a',
 'mind',
 'fuck',
 'movie',
 'for',
 'the',
 'teen',
 'generation',
 'that',
 'touches',
 'on',
 'a',
 'very',
 'cool',
 'idea',
 'but',
 'presents',
 'it',
 'in',
 'a',
 'very',
 'bad',
 'package',
 'which',
 'is',
 'what',
 'makes',
 'this',
 'review',
 'an',
 'even',
 'harder',
 'one',
 'to',
 'write',
 'since',
 'i',
 'generally',
 'applaud',
 'films',
 'which',
 'attempt',
 'to',
 'break',
 'the',
 'mold',
 'mess',
 'with',
 'your',
 'head',
 'and',
 'such',
 'lost',
 'highway',
 'memento',
 'but',
 'there',
 'are',
 'good',
 'and',
 'bad',
 'ways',

### Create a bag of words representation of the corpus
- Default setting gives unigrams, so below is unigram representation

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(new_list)
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### Creating bag but with Bi-grams representation

In [57]:
# Have to first make sentense representation of the words in order to split as bigrams
documents = []
for item in movie_reviews.sents():
    documents.append(' '.join(item))

vectorizer2 = CountVectorizer(ngram_range=(2,2))
X2 = vectorizer2.fit_transform(documents)
X2.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### Create a tf-idf representation
- Again, default ngram is a unigram

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizerT = TfidfVectorizer()
X3 = vectorizerT.fit_transform(new_list)
X3.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Now with Bi-gram representation

In [59]:
vectorizerT2 = TfidfVectorizer(ngram_range=(2,2))
X4 = vectorizerT2.fit_transform(documents)
X4.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## 3. Use Bayesian Classification to classify as either positive or negative review

### For bag of words unigram representation

In [61]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np
# Defining classes as 1 - positive review 0 - negative review
y = np.array([1, 0])

clf_uni = MultinomialNB()
clf_uni.fit(X, y)

ValueError: Found input variables with inconsistent numbers of samples: [1336843, 2]